development:
  adapter: postgresql
  encoding: unicode
  database: river_ridge_development
  username: <%= ENV[ 'DATABASE_USERNAME' ] %>
  password: <%= ENV[ 'DATABASE_PASSWORD' ] %>
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: river_ridge_test
  username: <%= ENV[ 'DATABASE_USERNAME' ] %>
  password: <%= ENV[ 'DATABASE_PASSWORD' ] %>
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: river_ridge_production
  username: <%= ENV[ 'DATABASE_USERNAME' ] %>
  password: <%= ENV[ 'DATABASE_PASSWORD' ] %>
  host: localhost
